"""user_tenseal_context

Revision ID: 1746173588
Revises: 1745984575
Create Date: 2025-05-02 15:13:08.212227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1746173588'
down_revision: Union[str, None] = '1745984575'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tenseal_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('context', sa.LargeBinary(length=16777216), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tenseal_context_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tenseal_context')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_tenseal_context_user_id'))
    )
    op.create_index(op.f('ix_user_tenseal_context_id'), 'user_tenseal_context', ['id'], unique=False)
    op.alter_column('user_profiles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_profiles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_profiles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_profiles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_user_tenseal_context_id'), table_name='user_tenseal_context')
    op.drop_table('user_tenseal_context')
    # ### end Alembic commands ###
