"""create database for saving user registered faces and it's encrypted embedding

Revision ID: 1746692750
Revises: 1746173588
Create Date: 2025-05-08 15:25:50.067216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1746692750'
down_revision: Union[str, None] = '1746173588'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_registered_faces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('real_content', sa.LargeBinary(length=16777216), nullable=False),
    sa.Column('rgb_content', sa.LargeBinary(length=16777216), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_registered_faces_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_registered_faces'))
    )
    op.create_index(op.f('ix_user_registered_faces_id'), 'user_registered_faces', ['id'], unique=False)
    op.create_table('user_encrypted_face_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(length=1048576), nullable=False),
    sa.Column('detection_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['user_registered_faces.id'], name=op.f('fk_user_encrypted_face_embeddings_source_file_id_user_registered_faces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_encrypted_face_embeddings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_encrypted_face_embeddings')),
    sa.UniqueConstraint('source_file_id', name=op.f('uq_user_encrypted_face_embeddings_source_file_id'))
    )
    op.create_index(op.f('ix_user_encrypted_face_embeddings_id'), 'user_encrypted_face_embeddings', ['id'], unique=False)
    op.alter_column('user_tenseal_context', 'context',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tenseal_context', 'context',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_encrypted_face_embeddings_id'), table_name='user_encrypted_face_embeddings')
    op.drop_table('user_encrypted_face_embeddings')
    op.drop_index(op.f('ix_user_registered_faces_id'), table_name='user_registered_faces')
    op.drop_table('user_registered_faces')
    # ### end Alembic commands ###
