"""add role_id to user model

Revision ID: 1747905537
Revises: 1747800216
Create Date: 2025-05-22 16:18:57.783309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1747905537'
down_revision: Union[str, None] = '1747800216'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles'))
    )
    op.create_index(op.f('ix_user_roles_role_name'), 'user_roles', ['role_name'], unique=False)
    op.alter_column('user_encrypted_face_embeddings', 'embedding',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=1048576),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'real_content',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'rgb_content',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=False)
    op.alter_column('user_tenseal_context', 'context',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=False)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_role_id_user_roles'), 'users', 'user_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_role_id_user_roles'), 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.alter_column('user_tenseal_context', 'context',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'rgb_content',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'real_content',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('user_encrypted_face_embeddings', 'embedding',
               existing_type=sa.LargeBinary(length=1048576),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_roles_role_name'), table_name='user_roles')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
