"""change user attendance model late_in and early_out to nullable

Revision ID: 1748251410
Revises: 1747905537
Create Date: 2025-05-26 16:23:30.898219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1748251410'
down_revision: Union[str, None] = '1747905537'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_attendances', 'late_in',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_attendances', 'early_out',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_encrypted_face_embeddings', 'embedding',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=1048576),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'real_content',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'rgb_content',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=False)
    op.alter_column('user_tenseal_context', 'context',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tenseal_context', 'context',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'rgb_content',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('user_registered_faces', 'real_content',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('user_encrypted_face_embeddings', 'embedding',
               existing_type=sa.LargeBinary(length=1048576),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    op.alter_column('user_attendances', 'early_out',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_attendances', 'late_in',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
